const phrases = [
    "Let's take it offline",
    "Let's put a pin on it",
    'Circle back',
    'Double Click',
    'Sorry, I was on mute',
    'Can you see my screen?',
    'Rock and roll',
    'push the needle',
    'where the rubber meets the road',
    "let's create a ticket for it",
    'Boil the ocean',
    'boots on the ground',
    'bottom up',
    'buy-in',
    'critical path',
    'deck',
    'deep dive',
    'happy path',
    'hard stop',
    'let me play this back',
    'low-hanging fruit',
    'On the beach / On the Bench',
    'push back',
    'straw man',
    '80/20',
    '20,000 feet',
    'Critical path',
    'Hit the Ground Running',
    'Mission-critical',
    'Thinking out of the box',
    'SME',
    'Takeaway',
    'Tighten Up',
    'Wordsmith',
];

export default phrases;